<a href="https://colab.research.google.com/github/RahulPaul1999/DS-Mini-Project/blob/main/DS_Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install ipython-autotime
%load_ext autotime

time: 2.58 ms (started: 2021-06-25 06:11:02 +00:00)


In [ ]:
# Install Bing Image Downloader
!pip install bing-image-downloader

time: 3.14 s (started: 2021-06-22 19:51:25 +00:00)


In [2]:
# Setting up OS Environment
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content/drive/MyDrive/Colab Notebooks/DS Mini Project'

time: 1.9 ms (started: 2021-06-25 06:21:49 +00:00)


In [12]:
# Project Folder
%cd'/content/drive/MyDrive/Colab Notebooks/DS Mini Project'

/content/drive/MyDrive/Colab Notebooks/DS Mini Project
time: 10.8 ms (started: 2021-06-25 06:25:07 +00:00)


In [13]:
DATADIR = '/content/drive/MyDrive/Colab Notebooks/DS Mini Project/train_data'
CATEGORIES = ['cats', 'dogs']

time: 1.34 ms (started: 2021-06-25 06:25:13 +00:00)


In [ ]:
# Downloading Images for Category 1
from bing_image_downloader import downloader
downloader.download("cats", limit=100, output_dir = DATADIR)

[%] Downloading Images to /content/drive/MyDrive/Colab Notebooks/DS Mini Project/train_data/cats


[!!]Indexing page: 1

[%] Indexed 100 Images on Page 1.


[%] Downloading Image #1 from https://miaustore.com/uk/wp-content/uploads/sites/3/2018/04/sad-cat.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://cdn.shortpixel.ai/client/q_lossy,ret_img,w_1000/https://www.ukpets.com/blog/wp-content/uploads/2018/05/cat.jpg
[%] File Downloaded !

[%] Downloading Image #3 from http://klyker.com/wp-content/uploads/2014/10/hellish-cats-32.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/originals/12/c8/4f/12c84fafbc0853a92326a312e0754452.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://itsalovelylife.com/wp-content/uploads/2015/05/cat-photos-1400x700.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/originals/6d/2d/02/6d2d02a6860d3f0ed30ea159f5c3cdf0.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https:/

In [ ]:
# Downloading Images for Category 2
downloader.download("dogs", limit=100, output_dir = DATADIR)

[%] Downloading Images to /content/drive/MyDrive/Colab Notebooks/DS Mini Project/train_data/dogs


[!!]Indexing page: 1

[%] Indexed 100 Images on Page 1.


[%] Downloading Image #1 from http://englishrussia.com/wp-content/uploads/2015/04/516.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://img1.grunge.com/img/gallery/false-facts-about-dogs-you-always-thought-were-true/intro.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://englishrussia.com/wp-content/uploads/2015/04/1114.jpg
[%] File Downloaded !

[%] Downloading Image #4 from http://englishrussia.com/wp-content/uploads/2015/04/532.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://img2.grunge.com/img/gallery/false-facts-about-dogs-you-always-thought-were-true/dogs-and-cats-just-cant-get-along.jpg
[%] File Downloaded !

[%] Downloading Image #6 from https://englishrussia.com/wp-content/uploads/2015/04/515.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://i.pinimg.com/origina

In [14]:
# Importing Necessary Libraries
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from skimage.io import imread
from skimage.transform import resize

target = []
images = []
flat_data = []

time: 1.09 s (started: 2021-06-25 06:25:21 +00:00)


In [15]:
# Preprocessing
for category in CATEGORIES:
  class_num = CATEGORIES.index(category) # using CATEGORIES index for Label Encoding
  path = os.path.join(DATADIR, category)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path, img))
    img_resized = resize(img_array, (150, 150, 3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_num)

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)    

time: 1min 40s (started: 2021-06-25 06:25:28 +00:00)


In [16]:
unique,count = np.unique(target, return_counts=True)
print(CATEGORIES,count)

['cats', 'dogs'] [100 100]
time: 2.34 ms (started: 2021-06-25 06:27:14 +00:00)


In [17]:
# saving Preprocessed Data In a Dataframe and csv file
dataframe = pd.DataFrame(flat_data,target) 

time: 1.59 ms (started: 2021-06-25 06:27:19 +00:00)


In [18]:
dataframe.to_csv('/content/drive/MyDrive/Colab Notebooks/DS Mini Project/train_data/cat_dog.csv')

time: 36.7 s (started: 2021-06-25 06:27:22 +00:00)


In [19]:
# importing the csv file
import pandas as pd
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DS Mini Project/train_data/cat_dog.csv')

time: 34.8 s (started: 2021-06-25 06:28:24 +00:00)


In [26]:
data.head(5)

Unnamed: 0         0         1  ...     67497     67498     67499
0           0  0.945098  0.960784  ...  0.715503  0.723346  0.719425
1           0  0.533333  0.468627  ...  0.298693  0.278431  0.200000
2           0  0.260784  0.229412  ...  0.307843  0.245098  0.115686
3           0  0.921569  0.921569  ...  0.878431  0.803922  0.675992
4           0  0.007843  0.027451  ...  0.031373  0.062745  0.094118

[5 rows x 67501 columns]

time: 128 ms (started: 2021-06-25 06:31:39 +00:00)


In [33]:
# Diving the dataframe into X and y
X = data.drop(['Unnamed: 0'], axis=1)
y = data['Unnamed: 0']

time: 71.9 ms (started: 2021-06-25 06:32:53 +00:00)


In [34]:
print("X shape: ", X.shape)
print("y shape: ", y.shape)

X shape:  (200, 67500)
y shape:  (200,)
time: 2.42 ms (started: 2021-06-25 06:32:57 +00:00)


In [48]:
# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.2)

time: 85.1 ms (started: 2021-06-25 06:38:26 +00:00)


In [49]:
print("X_train shape: ", X_train.shape)
print("y_train shape: ", y_train.shape)
print("X_test shape: ", X_test.shape)
print("y_test shape: ", y_test.shape)

X_train shape:  (160, 67500)
y_train shape:  (160,)
X_test shape:  (40, 67500)
y_test shape:  (40,)
time: 2.44 ms (started: 2021-06-25 06:38:33 +00:00)


Classifiers to be used
1. SVM
2. KNN
3. Random Forest Classifier
4. Decision Tree "
5. Log Reg
6. Naive Bayes
7. XGBoost

In [50]:
# Dictionary to store Accuracy Scores of different models
score = dict()

time: 1.17 ms (started: 2021-06-25 06:38:38 +00:00)


In [51]:
# SVC: Support Vector Classifier
from sklearn.svm import SVC
model_SVC = SVC()
model_SVC.fit(X_train, y_train)
y_pred_SVC = model_SVC.predict(X_test)
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(classification_report(y_test,y_pred_SVC))
print("Accuracy Score:", accuracy_score(y_test, y_pred_SVC))
print(confusion_matrix(y_test,y_pred_SVC))
score["SVC"] = accuracy_score(y_test, y_pred_SVC)

              precision    recall  f1-score   support

           0       0.59      0.59      0.59        22
           1       0.50      0.50      0.50        18

    accuracy                           0.55        40
   macro avg       0.55      0.55      0.55        40
weighted avg       0.55      0.55      0.55        40

Accuracy Score: 0.55
[[13  9]
 [ 9  9]]
time: 3.87 s (started: 2021-06-25 06:38:42 +00:00)


In [52]:
# KNN: K Nearest Neighbour
from sklearn.neighbors import KNeighborsClassifier
model_KNN = KNeighborsClassifier()
model_KNN.fit(X_train, y_train)
y_pred_KNN = model_KNN.predict(X_test)
print(confusion_matrix(y_test,y_pred_KNN))
print(f"Accuracy Score: {accuracy_score(y_test,y_pred_KNN)}")
print(classification_report(y_test,y_pred_KNN))
score["KNN"] = accuracy_score(y_test, y_pred_KNN)

[[15  7]
 [12  6]]
Accuracy Score: 0.525
              precision    recall  f1-score   support

           0       0.56      0.68      0.61        22
           1       0.46      0.33      0.39        18

    accuracy                           0.53        40
   macro avg       0.51      0.51      0.50        40
weighted avg       0.51      0.53      0.51        40

time: 1.61 s (started: 2021-06-25 06:38:51 +00:00)


In [53]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
model_RFC = RandomForestClassifier()
model_RFC.fit(X_train, y_train)
y_pred_RFC = model_RFC.predict(X_test)
print("Accuracy Score: ", accuracy_score(y_test, y_pred_RFC))
print(confusion_matrix(y_test,y_pred_RFC))
print(classification_report(y_test,y_pred_RFC))
score["RFC"] = accuracy_score(y_test, y_pred_RFC)

Accuracy Score:  0.6
[[ 9 13]
 [ 3 15]]
              precision    recall  f1-score   support

           0       0.75      0.41      0.53        22
           1       0.54      0.83      0.65        18

    accuracy                           0.60        40
   macro avg       0.64      0.62      0.59        40
weighted avg       0.65      0.60      0.58        40

time: 1.47 s (started: 2021-06-25 06:39:01 +00:00)


In [54]:
# XGBoost
from xgboost import XGBClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
model_XGB = XGBClassifier()
model_XGB.fit(X_train, y_train)
y_pred_XGB = model_XGB.predict(X_test)
print(f"XGB Score: {model_XGB.score(X_test, y_test)}")
print(f"Confusion Matrix: {confusion_matrix(y_test,y_pred_XGB)}")
print(f"Accuracy Score: {accuracy_score(y_test,y_pred_XGB)}")
print(f"Classification Report: {classification_report(y_test,y_pred_XGB)}")
score["XGB"] = accuracy_score(y_test, y_pred_XGB)

XGB Score: 0.45
Confusion Matrix: [[10 12]
 [10  8]]
Accuracy Score: 0.45
Classification Report:               precision    recall  f1-score   support

           0       0.50      0.45      0.48        22
           1       0.40      0.44      0.42        18

    accuracy                           0.45        40
   macro avg       0.45      0.45      0.45        40
weighted avg       0.45      0.45      0.45        40

time: 1min 9s (started: 2021-06-25 06:39:07 +00:00)


In [55]:
# Naive Bayes
from sklearn.naive_bayes import GaussianNB
model_NB = GaussianNB()
model_NB.fit(X_train, y_train)
y_pred_NB = model_NB.predict(X_test)
print(f"{confusion_matrix(y_test,y_pred_NB)}")
print(f"Accuracy Score: {accuracy_score(y_test,y_pred_NB)}")
print(f"{classification_report(y_test,y_pred_NB)}")
score["NB"] = accuracy_score(y_test, y_pred_NB)

[[11 11]
 [ 5 13]]
Accuracy Score: 0.6
              precision    recall  f1-score   support

           0       0.69      0.50      0.58        22
           1       0.54      0.72      0.62        18

    accuracy                           0.60        40
   macro avg       0.61      0.61      0.60        40
weighted avg       0.62      0.60      0.60        40

time: 376 ms (started: 2021-06-25 06:40:22 +00:00)


In [56]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
model_LR = LogisticRegression()
model_LR.fit(X_train,y_train)
y_pred_LR = model_LR.predict(X_test)
print(f"{confusion_matrix(y_test,y_pred_LR)}")
print(f"Accuracy Score: {accuracy_score(y_test,y_pred_LR)}")
print(f"{classification_report(y_test,y_pred_LR)}")
score["LR"] = accuracy_score(y_test, y_pred_LR)

[[14  8]
 [ 4 14]]
Accuracy Score: 0.7
              precision    recall  f1-score   support

           0       0.78      0.64      0.70        22
           1       0.64      0.78      0.70        18

    accuracy                           0.70        40
   macro avg       0.71      0.71      0.70        40
weighted avg       0.71      0.70      0.70        40

time: 4.54 s (started: 2021-06-25 06:40:25 +00:00)


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [57]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
model_DT = DecisionTreeClassifier()
model_DT.fit(X_train,y_train)
y_pred_DT = model_DT.predict(X_test)
print(f"{confusion_matrix(y_test,y_pred_DT)}")
print(f"Accuracy Score: {accuracy_score(y_test,y_pred_DT)}")
print(f"{classification_report(y_test,y_pred_DT)}")
score["DT"] = accuracy_score(y_test, y_pred_DT)

[[14  8]
 [11  7]]
Accuracy Score: 0.525
              precision    recall  f1-score   support

           0       0.56      0.64      0.60        22
           1       0.47      0.39      0.42        18

    accuracy                           0.53        40
   macro avg       0.51      0.51      0.51        40
weighted avg       0.52      0.53      0.52        40

time: 4.59 s (started: 2021-06-25 06:40:34 +00:00)


In [58]:
score

{'DT': 0.525,
 'KNN': 0.525,
 'LR': 0.7,
 'NB': 0.6,
 'RFC': 0.6,
 'SVC': 0.55,
 'XGB': 0.45}

time: 4.73 ms (started: 2021-06-25 06:40:44 +00:00)


Logistic Regression Classifier Algorithm gives the highest accuracy score of 70%